(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='yawarakaku-v1'; const defaults={favorites:[],recent:[]};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.favorites)&&Array.isArray(x.recent)?x:{...defaults}}catch{return {...defaults}}}
let saved=load(), selected=null, category='all', audience='同僚', tone='soft', activeTab='favorites', deferredInstall;
const audiences=['上司','同僚','部下','取引先','友達','家族・恋人'];
const tones=[['soft','やわらかく','角を丸く'],['polite','丁寧に','きちんと敬語'],['firm','しっかり','本音は明確に']];
const view=name=>{['home','builder','results','library'].forEach(v=>$('#'+v+'-view').hidden=v!==name);$$('[data-nav]').forEach(a=>a.toggleAttribute('aria-current',a.dataset.nav===name));scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#main').focus({preventScroll:true})};
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{toast('保存できませんでした')};updateCounts()};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),1800)}
function renderCategories(){$('#quick-row').innerHTML=CATEGORIES.map(c=>`<button type="button" data-cat="${c[0]}" aria-pressed="${category===c[0]}">${c[1]}</button>`).join('')}
function renderPhrases(){const q=$('#search').value.trim().toLowerCase();const rows=PHRASES.filter(p=>(category==='all'||p.category===category)&&(!q||[p.raw,p.categoryLabel,p.soft,p.polite,p.firm].join(' ').toLowerCase().includes(q)));$('#result-count').textContent=`${rows.length}件`;$('#phrase-list').innerHTML=rows.map(p=>`<button class="phrase" type="button" data-id="${p.id}"><span><small>${p.categoryLabel}</small>${p.raw}</span><b aria-hidden="true">→</b></button>`).join('');$('#search-empty').hidden=rows.length>0}
function choose(p){selected=p;makeResults()}
function renderChoices(){$('#audience-choices').innerHTML=audiences.map(a=>`<button type="button" data-audience="${a}" aria-pressed="${a===audience}">${a}</button>`).join('');$('#tone-choices').innerHTML=tones.map(t=>`<button type="button" data-tone="${t[0]}" aria-pressed="${t[0]===tone}"><strong>${t[1]}</strong><small>${t[2]}</small></button>`).join('')}
function adjusted(text){if(audience==='上司'||audience==='取引先')return text;if(audience==='友達'||audience==='家族・恋人')return text.replace(/いただけますか/g,'もらえる？').replace(/お願いします/g,'お願い').replace(/申し訳ありません/g,'ごめんね');return text}
function makeResults(){const order=tone==='soft'?['soft','polite','firm']:tone==='polite'?['polite','soft','firm']:['firm','polite','soft'];const labels={soft:'ふんわり',polite:'きちんと',firm:'はっきり'};$('#result-context').textContent=`${audience}へ・${tones.find(t=>t[0]===tone)[1]}`;$('#result-cards').innerHTML=order.map((k,i)=>{const text=adjusted(selected[k],i);return `<article class="result-card"><div><span>0${i+1}</span><small>${labels[k]}</small></div><p>${text}</p><div class="result-actions"><button type="button" data-copy="${encodeURIComponent(text)}">コピー</button><button class="heart" type="button" data-fav="${encodeURIComponent(text)}" aria-label="お気に入りに追加" aria-pressed="${saved.favorites.some(x=>x.text===text)}">♡</button></div></article>`}).join('');saved.recent=[{raw:selected.raw,audience,tone,date:Date.now()},...saved.recent.filter(x=>x.raw!==selected.raw)].slice(0,20);persist();view('results');location.hash='results'}
function copy(text){const done=()=>toast('コピーしました。あとは送るだけ。');if(navigator.clipboard&&isSecureContext)navigator.clipboard.writeText(text).then(done).catch(()=>fallback());else fallback();function fallback(){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();try{document.execCommand('copy');done()}catch{toast('長押ししてコピーしてください')}t.remove()}}
function toggleFav(text,button){const i=saved.favorites.findIndex(x=>x.text===text);if(i>=0){saved.favorites.splice(i,1);button?.setAttribute('aria-pressed','false');toast('お気に入りから外しました')}else{saved.favorites.unshift({text,raw:selected?.raw||'',date:Date.now()});button?.setAttribute('aria-pressed','true');toast('お気に入りに保存しました')}persist()}
function updateCounts(){$('#fav-count').textContent=saved.favorites.length;$('#recent-count').textContent=saved.recent.length}
function renderLibrary(){const items=saved[activeTab];$('#library-list').innerHTML=items.length?items.map((x,i)=>activeTab==='favorites'?`<article class="saved-card"><small>${x.raw?'「'+x.raw+'」から':''}</small><p>${x.text}</p><div><button data-copy="${encodeURIComponent(x.text)}">コピー</button><button data-remove="${i}" aria-label="お気に入りから削除">削除</button></div></article>`:`<button class="recent-card" data-recent="${i}"><small>${x.audience}へ</small><strong>${x.raw}</strong><span>もう一度 →</span></button>`).join(''):`<div class="empty"><span>${activeTab==='favorites'?'♡':'○'}</span><h2>${activeTab==='favorites'?'まだ保存はありません':'履歴はまだありません'}</h2><p>使った言葉が、ここにそっと残ります。</p></div>`;updateCounts()}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.cat!==undefined){category=b.dataset.cat;renderCategories();renderPhrases()}if(b.dataset.id)choose(PHRASES.find(p=>p.id===b.dataset.id));if(b.dataset.audience){audience=b.dataset.audience;renderChoices()}if(b.dataset.tone){tone=b.dataset.tone;renderChoices()}if(b.id==='make-button')makeResults();if(b.dataset.copy)copy(decodeURIComponent(b.dataset.copy));if(b.dataset.fav)toggleFav(decodeURIComponent(b.dataset.fav),b);if(b.dataset.back!==undefined){view('home');location.hash='home'}if(b.dataset.backToBuilder!==undefined){$('#builder-title').textContent='「'+selected.raw+'」';renderChoices();view('builder');location.hash='make'}if(b.id==='restart-button'){view('home');location.hash='home'}if(b.dataset.nav==='home')view('home');if(b.dataset.nav==='library'){renderLibrary();view('library')}if(b.dataset.tab){activeTab=b.dataset.tab;$$('[role=tab]').forEach(t=>t.setAttribute('aria-selected',t===b));renderLibrary()}if(b.dataset.remove!==undefined){saved.favorites.splice(+b.dataset.remove,1);persist();renderLibrary()}if(b.dataset.recent!==undefined){const x=saved.recent[+b.dataset.recent];selected=PHRASES.find(p=>p.raw===x.raw);if(selected){audience=x.audience;tone=x.tone;choose(selected)}}if(b.id==='clear-history'&&saved.recent.length){saved.recent=[];persist();renderLibrary();toast('履歴を消去しました')}if(b.id==='install-button'&&deferredInstall){deferredInstall.prompt();deferredInstall=null;b.hidden=true}});
$('#search').addEventListener('input',renderPhrases);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install-button').hidden=false});
window.addEventListener('hashchange',()=>{if(location.hash==='#library'){renderLibrary();view('library')}else if(!['#make','#results'].includes(location.hash))view('home')});
renderCategories();renderPhrases();updateCounts();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));if(location.hash==='#library'){renderLibrary();view('library')}else if(['#make','#results'].includes(location.hash)){history.replaceState(null,'','#home');view('home')}
})();
